language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t jangminju/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script: 
  - docker run -e CI=true jangminju/react-test-app npm run test

after_success:
  - docker build -t jangminju/docker-frontend ./frontend
  - docker build -t jangminju/docker-backend  ./backend
  - docker build -t jangminju/docker-nginx    ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jangminju/docker-frontend
  - docker push jangminju/docker-backend
  - docker push jangminju/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-fullstack-app"
  env: "Docker-fullstack-app-env"
  bucket_name: elasticbeanstalk-ap-southeast-2-450733265403
  bucket_path: "docker-fullstack-app"
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY